version: 2

sources:

  - name: tutorial # name of the source 
    schema: public # this is the schema our raw data lives in
    database: dbt # this is the name of our database

    quoting:
      database: false
      schema: false
      identifier: false

    freshness: # default freshness
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: created_at

    tables:
      - name: users 
        loaded_at_field: created_at
        description: Contains raw user personal information from source Tutorial - dbt database. One row per unique user.
        freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
      - name: addresses
        description: Contains raw address information from source Tutorial - dbt database. One row per unique address.
        freshness: null # do not check freshness for this table
      - name: products
        description: Contains raw product details from source Tutorial - dbt database. One row per unique product.
        freshness: null # do not check freshness for this table
      - name: orders
        loaded_at_field: created_at
        description: Contains raw order details from source Tutorial - dbt database. One row per unique order.
        freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
      - name: order_items
        description: Contains raw order_item details from source Tutorial - dbt database. One order_id can have one or more items.
        freshness: null # do not check freshness for this table
      - name: events
        loaded_at_field: created_at
        description: Contains raw events from source Tutorial - dbt database. One row per event.
      - name: promos
        description: Contains raw promo details from source Tutorial - dbt database. One row per unique promo.
        freshness: null # do not check freshness for this table