
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_greenery'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'greenery'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"



# Configuring models
# Full documentation: https://docs.getdbt.com/docså/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  #my_new_project:
    # Config indicated by + and applies to all files under models/example/
    1_data_platform_lake:
      +store_failures: true  # all tests
    2_data_platform_staging:
      +materialized: view
      +store_failures: true  # all tests
    3_data_platform_integration:
      +materialized: view
    4_data_platform_presentation:
      +materialized: table

tests:
  +store_failures: true  # all tests