
version: 2

  
models:
  - name: stg_tutorial_users
    description: one-to-one copy of user info from tutorial.users table
    columns:
      - name: user_id
        description: The primary key for this table. Refers to the id field in tutorial.users table.
        tests:
          - unique
          - not_null
      - name: user_guid
        description: The globally unique identifier of the user.
        tests:
          - not_null
      - name: user_first_name
        description: User's first name.
      - name: user_last_name
        description: User's last name.
      - name: user_email
        description: User's email.
      - name: user_phone_number
        description: User's phone number.
      - name: user_address_guid
        description: The globally unique identifier of the user's address.
        tests:
          - relationships:
              to: ref('stg_tutorial_addresses')
              field: address_guid
      - name: user_created_at
        description: The date and time when the user information was created from the source. 
        tests:
          - not_null
      - name: user_updated_at
        description: The date and time when the user information was updated from the source. 


  - name: stg_tutorial_addresses
    description: one-to-one copy of address info from tutorial.addresses table
    columns:
      - name: address_id
        description: The primary key for this table
        tests:
          - unique
          - not_null
      - name: address_guid
        description: The globally unique identifier of the address.
        tests:
          - not_null
      - name: address
        description: the house number and street information.
      - name: zipcode
        description: zipcode address eg. 92056
      - name: state   
        description: state address eg. California
        tests:
          - not_null
      - name: country
        description: country address eg. United States
        tests:
          - not_null

          
  - name: stg_tutorial_products
    description: one-to-one copy of product info from tutorial.products table
    columns:
      - name: product_id
        description: The primary key for this table
        tests:
          - not_null
          - unique
      - name: product_guid   
        description: The globally unique identifier of the product.
        tests:
          - not_null
      - name: product_name
        description: The name of the product.
      - name: product_price   
        description: The price of the product.
        tests:
          - positive_values
          - not_null
      - name: product_quantity
        description: The quantity of the product.
        tests:
          - positive_values
          - not_null


  - name: stg_tutorial_promos
    description: one-to-one copy of promo details from tutorial.promos table
    columns:
      - name: promo_id
        description: The primary key for this table.
        tests:
          - unique
          - not_null
      - name: promo_code
        description: The promotional code 1 eg. (task-force, instruction set).
        tests:
          - not_null
      - name: promo_discount_percentage
        description: Refers to the promotional discount applied to the product.
        tests: 
          - positive_values
          - not_null
      - name: promo_status
        description: Refers to the status of the promotion.
        tests:
          - accepted_values:
              values: ['active', 'inactive']

  - name: stg_tutorial_orders
    description: one-to-one copy of order details from tutorial.orders table
    columns:
      - name: order_id
        description: The primary key for this table.
        tests:
          - unique
          - not_null
      - name: order_guid
        description: The globally unique identifier of the order.
        tests:
          - unique
          - not_null
      - name: order_status
        description: The status of the order.
        tests:
          - accepted_values:
              values: ['pending', 'preparing', 'shipped', 'delivered']
      - name: order_created_at
        description: The data and time when the user placed the order.
      - name: promo_code
        description: Promo key globaly unique identifier.
      - name: order_cost
        description: Refers to the cost of the order.
        tests:
          - positive_values
          - not_null
      - name: shipping_cost
        description: Refers to the shipping costs.
        tests:
          - positive_values
      - name: shipping_service
        description: The shipping service provider.
      - name: order_total
        description: The total cost of the order.
        tests:
          - positive_values
          - not_null
      - name: user_guid
        description: The globally unique identifier of the user.
        tests:
          - relationships:
              to: ref('stg_tutorial_users')
              field: user_guid
      - name: delivery_address_guid
        description: The globally unique identifier of the user address where the order will be delivered.
        tests:
          - relationships:
              to: ref('stg_tutorial_addresses')
              field: address_guid
      - name: tracking_guid
        description: The globally unique identifier of the tracking use to track the status of the order.
      - name: estimated_delivery_at
        description: The date and time when then order is expected to be delivered.
      - name: delivered_at
        description:  The date and time when then order was delivered.



  - name: stg_tutorial_order_items
    description: one-to-one copy of order item details from tutorial.order_items table
    columns:
      - name: order_item_id
        description: The primary key for this table
        tests:
          - unique
          - not_null
      - name: order_product_guid
        description: Combination of order_guid and product_guid separated by a a dash (-).
      - name: order_guid
        description: The globally unique identifier of the order.
        tests:
          - relationships:
              to: ref('stg_tutorial_orders')
              field: order_guid
      - name: product_guid
        description: The globally unique identifier of the product.
        tests:
          - relationships:
              to: ref('stg_tutorial_products')
              field: product_guid
      - name: order_quantity
        description: Total number of products ordered.
        tests:
          - positive_values
          - not_null


  - name: stg_tutorial_events
    description: one-to-one copy of events data from tutorial.events table
    columns:
      - name: event_id
        description:  "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: event_guid
        description:  The globally unique identifier of the event.
        tests:
          - unique
          - not_null
      - name: session_guid
        description: The globally unique identifier of the session.
        tests:
          - not_null
      - name: event_type
        description: The type of the event performed eg. checkout, add_to_cart, account_created, package_shipped.
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['page_view','add_to_cart','delete_from_cart','checkout','package_shipped']
      - name: event_timestamp
        description: The date and time of when the event occurred.
        tests:
          - not_null
      - name: user_guid
        description: The globally unique identifier of the user.
        tests:
          - relationships:
              to: ref('stg_tutorial_users')
              field: user_guid
      - name: product_guid
        description: The globally unique identifier of the product.
      - name: page_url
        description: The url of the page the user had visited within the session.

